name: CI

on:
  push:

jobs:
  staticcheck:
    name: Staticcheck
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x

      - name: Get source
        uses: actions/checkout@v3

      - name: Go get staticcheck
        run: go mod download

      - name: Golint
        run: go run honnef.co/go/tools/cmd/staticcheck ./...
